=== yangqinjiang/CodeOfLearningXML/xmlTest/src/Myfile.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT FILESYSTEM (MYFILE+)>
<!ELEMENT MYFILE (TITLE,AUTHOR,EMAIL,PageAuthor)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ATTLIST AUTHOR 
			AUTHORID CDATA #REQUIRED>
<!ELEMENT EMAIL (#PCDATA)>
<!ELEMENT PageAuthor (#PCDATA)>
<!ATTLIST PageAuthor
	name CDATA #IMPLIED
	age CDATA #IMPLIED
	tel CDATA #REQUIRED
	job CDATA #FIXED "PageAuthor"
	favorite CDATA "onLine">

=== yangqinjiang/CodeOfLearningXML/xmlTest/bin/FileSystem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FILESYSTEM SYSTEM "Myfile.dtd">
<FILESYSTEM>
	<MYFILE>
		<TITLE>filename</TITLE>
		<AUTHOR AUTHORID="">you</AUTHOR>
		<EMAIL>email at email.com</EMAIL>
		<PageAuthor tel="123456"></PageAuthor>
	</MYFILE>
	<MYFILE>
		<TITLE></TITLE>
		<AUTHOR AUTHORID=""></AUTHOR>
		<EMAIL></EMAIL>
		<PageAuthor tel="123456"></PageAuthor>
	</MYFILE>
</FILESYSTEM>
